/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.itcall;

import org.junit.jupiter.api.Test;
import org.springframework.util.Assert;

import com.itcall.Application;

public class ApplicationTest {

	@Test
	public void testSomeLibraryMethod() {
		Application classUnderTest = new Application();
		Assert.isTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
	}
}
